from pathlib import Path

from pydantic_settings import BaseSettings, SettingsConfigDict

# Load repo root .env then backend/.env (later wins). Works for Docker (cwd /app) and native dev.
_cfg = Path(__file__).resolve()
_repo_root = _cfg.parents[2]
_backend_root = _cfg.parents[1]
_env_files = tuple(
    str(p)
    for p in (_repo_root / ".env", _backend_root / ".env")
    if p.is_file()
)


class Settings(BaseSettings):
    model_config = SettingsConfigDict(
        env_file=_env_files if _env_files else None,
        env_file_encoding="utf-8",
    )

    database_url: str = "postgresql+psycopg2://postgres:postgres@localhost:5432/portfolio_intel"
    openai_api_key: str = ""
    firebase_project_id: str = ""
    resend_api_key: str = ""
    slack_bot_token: str = ""
    app_base_url: str = "http://localhost:8000"
    context_provider: str = "fallback"
    context_model: str = "gpt-4.1-mini"
    newsapi_key: str = ""
    newsapi_url: str = "https://newsapi.org/v2/everything"
    newsapi_query: str = "private equity OR portfolio company OR M&A OR funding"
    newsapi_page_size: int = 25
    # Free Developer plan is ~100 requests/day; each ingest page is one HTTP call — keep this low.
    newsapi_max_pages: int = 2
    # Context-driven ingest: collect up to N keywords from profiles, batch into NewsAPI `q` (max 500 chars each),
    # then fetch up to `newsapi_ingest_target_articles` unique articles. Company↔article fit is done in process (semantic/LLM).
    newsapi_use_context_query: bool = True
    newsapi_query_max_chars: int = 500
    newsapi_context_keyword_budget: int = 40
    newsapi_ingest_target_articles: int = 40
    newsapi_max_request_batches: int = 8
    newsapi_context_sort_by: str = "relevancy"
    # When True, NewsAPI keywords are generated by Ollama from full context snapshots with equal per-profile quotas.
    # When False, or if Ollama fails, the heuristic term harvest (_collect_context_keywords) is used.
    newsapi_use_ollama_keywords: bool = True
    newsapi_ollama_keyword_timeout: float = 90.0
    # Two-phase ingest: (1) direct name/product/competitor terms → NewsAPI, (2) broad context terms → NewsAPI,
    # (3) brief Ollama semantic filter on broad-only articles. If False, uses legacy single keyword-batch flow.
    newsapi_two_phase_ingest: bool = True
    newsapi_direct_term_max: int = 28
    newsapi_broad_term_max: int = 48
    newsapi_direct_article_cap: int = 18
    newsapi_broad_article_cap: int = 32
    newsapi_max_batches_direct: int = 5
    newsapi_max_batches_broad: int = 8
    # Brief ingest-time semantic filter (Ollama): small batches, short snippets, low token cap.
    newsapi_semantic_enabled: bool = True
    newsapi_semantic_batch_size: int = 10
    newsapi_semantic_snippet_chars: int = 200
    newsapi_semantic_context_max_chars: int = 3200
    newsapi_semantic_ollama_num_predict: int = 280
    newsapi_semantic_timeout: float = 48.0
    newsapi_semantic_min_score: float = 0.42
    stage1_max_fetch: int = 1000
    stage1_candidate_limit: int = 250
    stage1_days_back: int = 7
    ollama_base_url: str = "http://localhost:11434"
    ollama_model: str = "llama3.1:8b"


settings = Settings()

